server:
  contextPath: /V1
  port: 5511

spring:
  redis:
    host: redislocal
    port: 6379

logging:
  file: ./logs/service.log
  level:
    root: info
    br.com.sysmap: info
    org.apache.camel: info
  pattern:
    file: "[%d{ISO8601}] %-5level %-40.40c{1.} : %m%ex%n"

application:
  path:
    # API Swagger
    api-doc: /api-doc
    api-title: User API
    api-version: 0.0.1-SNAPSHOT

    # Custom REST services
    service-request-type: /service-request-type
    service-request-type-desc: Customer Self Empowered Rest Service

  third-party:
    service-request-type-endpoint: http://localhost:8080

  queues:
    service-request-type-search: rabbitmq://rabbitmqlocal:5672/adapter.service.request.type?username=guest&password=guest&queue=adapter.service.request.type.search&exchangeType=direct&routingKey=search.v1&autoDelete=false&durable=true
